# Generated by Django 2.1.2 on 2018-10-12 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('nroSoc', models.IntegerField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=15)),
                ('apellido', models.CharField(max_length=15)),
            ],
        ),
    ]
